spring:
  datasource:
    url: jdbc:h2:mem:hogwarts
    username: sa
    password:
    driver-class-name: org.h2.Driver
  security:
    user:
      name: admin
      password: admin
jpa:
  show-sql: true

api:
  endpoint:
    base-url: /api/v1